### ISSUE TITLE
Title Bar Obscures Content

### ISSUE THREAD

**Issue by eehlers** [BlackrockDigital/startbootstrap-one-page-wonder#1]
when i click on the link in the title bar, it scrolls down to the relevant page heading, but it scrolls down too far, such that the title bar obscures the top of the heading.  how can i make it scroll down less so that the chosen heading is fully visible?

**Comment by mattmill98** [comment]
i have the same problem

**Comment by eehlers** [comment]
Ah good, so it's not just me, thanks for the confirmation.

Here is a screenshot of what I see when I go to the Live Preview and click About:

https://dl.dropboxusercontent.com/u/75778595/one_page_wonder_bug.png

I'm on Windows 7 and I get the same behavior in Chrome version 43.0.2357.81 as well as Firefox and IE.

Author?  Any idea how to fix this?  Of all of the bootstrap examples, this one is the closest to what I need, but I can't use it with this bug.

**Comment by mattmill98** [comment]
Yeah thats exactly what mine looks like

**Comment by mattmill98** [comment]
You found a fix yet? @eehlers

**Comment by haydgately** [comment]
made sure the id is in the feature divider? 

<hr class="featurette-divider"  id="about">

Mine jumped down less when I put it there instead of featurette but could be wrong!

**Comment by eehlers** [comment]
would be nice if the autheor could just fix it.

**Comment by davidtmiller** [comment]
Anyone come up with a fix for this?

**Comment by desttinghim** [comment]
This has to do with the title bar being 50px high. When jumping to content using a link, the title bar is not factored in. A couple methods to solve this are listed here: http://nicolasgallagher.com/jump-links-and-viewport-positioning/demo/

**Comment by hugoploeg** [comment]
What you can doe is change the margin, this is what I did to fix it.

`
.featurette-image.pull-left {
    margin-right: 40px;
    margin-top:100px;
}
`
`
.featurette-image.pull-right {
    margin-left: 40px;
    margin-top:100px;
}`
`.featurette-heading {
    font-size: 50px;
    margin-top:100px;
}`

Regards,

**Comment by Hugo1908** [comment]
Ok, what I have done to fix it for me, is the following.
For desktop I have add, the following in the css:

I have add the margin-top

`.featurette-image.pull-left {
    margin-right: 40px;
    margin-top:100px;
}`

`.featurette-image.pull-right {
    margin-left: 40px;
    margin-top:100px;
}`

`.featurette-heading {
    font-size: 50px;
    margin-top:100px;
}`

And in de index for the mobile part I have set the menu so that it will collaps after clicking

` <script>
    $(document).ready(function () {
  $(".navbar-nav li a").click(function(event) {
    $(".navbar-collapse").collapse('hide');
  });
});
</script>`

**Comment by davidtmiller** [comment]
This should be fixed in #11
